apiVersion: apps/v1
kind: Deployment
metadata:
  name: betmawrik-test
  labels:
    app: betmawrik-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: betmawrik-test
  template:
    metadata:
      labels:
        app: betmawrik-test
    spec:
      containers:
        - name: betmawrik-test
          image: betmawrik-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production