apiVersion: apps/v1
kind: Deployment
metadata:
  name: betmavrik-test
  labels:
    app: betmavrik-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: betmavrik-test
  template:
    metadata:
      labels:
        app: betmavrik-test
    spec:
      containers:
        - name: betmavrik-test
          image: betmavrik-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production